version: '3.8'

networks:
  default:
    name: fitness-tracker-network
    ipam:
      driver: default
      config:
        - subnet: 172.12.0.0/16


services:

  pg:
    container_name: db-fitness-tracker
    image: postgres:12
    restart: always
    mem_limit: 300M
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "40144:5432"
    volumes:
      - pg:/var/lib/postgresql/data
      - ./pg-init/init.sql:/docker-entrypoint-initdb.d/create-users.sql

volumes:
  pg:
    driver: local